name: Draft PR

on:
  push:
    branches-ignore: [main]

permissions:
  contents: read

jobs:
  draft:
    uses: PineappleEmperor/release-flow/.github/workflows/auto-draft-pr.yml@aa2b6aaf8dadccd1f6ed5c65df774cf5f96091ae # v1.1.4
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
