name: Draft PR

on:
  push:
    branches-ignore: [main]

permissions:
  contents: read

jobs:
  draft:
    uses: PineappleEmperor/release-flow/.github/workflows/auto-draft-pr.yml@7bfc333373cc6f5b396e0e786588e57dae033fdb # v1.1.3
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
