name: Lint PR

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions: {}

jobs:
  lint:
    permissions:
      pull-requests: read
    uses: PineappleEmperor/release-flow/.github/workflows/lint-pr.yml@87305e56bf921fe8728a2b448b112b06da6cc082 # v1.1.1
