name: Lint PR

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened]

permissions: {}

jobs:
  lint:
    permissions:
      pull-requests: read
    uses: PineappleEmperor/release-flow/.github/workflows/lint-pr.yml@7bfc333373cc6f5b396e0e786588e57dae033fdb # v1.1.3
