name: PR Checks

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pr-checks-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pr:
    uses: PineappleEmperor/release-flow/.github/workflows/pr-checks.yml@7bfc333373cc6f5b396e0e786588e57dae033fdb # v1.1.3
