name: PR Checks

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pr-checks-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pr:
    uses: PineappleEmperor/release-flow/.github/workflows/pr-checks.yml@87305e56bf921fe8728a2b448b112b06da6cc082 # v1.1.1
