name: Release Drafter

on:
  push:
    branches: [main]
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: PineappleEmperor/release-flow/.github/workflows/release-drafter.yml@87305e56bf921fe8728a2b448b112b06da6cc082 # v1.1.1
